"""Add connections table and control automation bindings

Revision ID: 30e1acda9687
Revises: f1420610d56a
Create Date: 2026-10-02 22:51:23.110232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30e1acda9687'
down_revision: Union[str, Sequence[str], None] = 'f1420610d56a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connections',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('GITHUB', name='connection_provider'), nullable=False),
    sa.Column('account_login', sa.String(length=300), nullable=False),
    sa.Column('encrypted_token', sa.Text(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connections_organization_id'), 'connections', ['organization_id'], unique=False)
    op.add_column('controls', sa.Column('automation_connection_id', sa.UUID(), nullable=True))
    op.add_column('controls', sa.Column('automation_check_key', sa.String(length=100), nullable=True))
    op.add_column('controls', sa.Column('automation_target', sa.String(length=300), nullable=True))
    op.create_foreign_key(
        'fk_controls_automation_connection_id', 'controls', 'connections', ['automation_connection_id'], ['id'], ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_controls_automation_connection_id', 'controls', type_='foreignkey')
    op.drop_column('controls', 'automation_target')
    op.drop_column('controls', 'automation_check_key')
    op.drop_column('controls', 'automation_connection_id')
    op.drop_index(op.f('ix_connections_organization_id'), table_name='connections')
    op.drop_table('connections')
    # ### end Alembic commands ###
